# .travis.yml
# Configure Travis CI service for http://github.com/LASzip
language: cpp

sudo: required
services: docker

compiler:
  - g++
  - clang

after_success:
  - echo "secure travis:" "$TRAVIS_SECURE_ENV_VARS"
  - sh -c 'if test "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "docker-docbuild"; then echo "publish website"; ./scripts/ci/build_docs.sh; ./scripts/ci/add_aws_credentials.sh; ./scripts/ci/deploy_website.sh $TRAVIS_BUILD_DIR/doc/build; fi'

before_install: ./scripts/ci/docker.sh

script: ./scripts/ci/script.sh

notifications:
  on_success: always # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
  irc: "chat.freenode.net#pdal"
  # Uncomment and edit below for notifications by e-mail
  #email:
  #  recipients:
  #    - howard@hobu.co

